# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Products
    weight: 20
    hasChildren: true
  - parent: Products
    name: Devices
    url: devices/
  - parent: Products
    name: Sensors
    url: sensors/
  - name: Customake
    url: customake/
    weight: 30
  - name: About us
    url: about-us/
    weight: 40

